---
- hosts: master
  gather_facts: no
  tasks:
    - set_fact:
        rhsso_namespace: "sso"
    - name: Retrieve cluster route subdomain
      slurp:
        src: "{{ eval_openshift_master_config_path }}"
      register: openshift_master_config
      become: yes

    - name: Retrieve RH-SSO admin user password
      shell: oc get dc/sso -o jsonpath='{.spec.template.spec.containers[?(@.name=="sso")].env[?(@.name=="SSO_ADMIN_PASSWORD")].value}' -n {{ rhsso_namespace }}
      register: rhsso_admin_password_cmd


    - name: Retrieve RH-SSO admin user name
      shell: oc get dc/sso -o jsonpath='{.spec.template.spec.containers[?(@.name=="sso")].env[?(@.name=="SSO_ADMIN_USERNAME")].value}' -n {{ rhsso_namespace }}
      register: rhsso_admin_user_cmd

    - name: Retrieve 3Scale admin auth token
      shell: oc describe dc/system-app -n 3scale | grep ADMIN_ACCESS_TOKEN | tail -1 | awk '{print $2}'
      register: admin_auth_config

    - set_fact:
        threescale_admin_token: "{{ admin_auth_config.stdout }}"

    - name: Retrieve 3Scale master auth token
      shell:  oc describe dc/system-app -n 3scale | grep MASTER_ACCESS_TOKEN | head -1 | awk -F '"' '{print $2}'
      register: master_auth_config

    - set_fact:
        threescale_admin_token: "{{ admin_auth_config.stdout }}"        
    - set_fact:
        threescale_master_token: "{{master_auth_config.stdout}}"

    - set_fact:
        rhsso_admin_username: "{{rhsso_admin_user_cmd.stdout}}"

    - set_fact:
        oc_apps_domain: "{{ (openshift_master_config['content'] | b64decode | from_yaml)['routingConfig']['subdomain'] }}"

    - set_fact:
        rhsso_admin_password: "{{rhsso_admin_password_cmd.stdout}}"

    - add_host:
        name: SHARED_VARS
        rhsso_admin_username: "{{ rhsso_admin_username }}"
        rhsso_admin_password: "{{ rhsso_admin_password }}"
        oc_apps_domain: "{{ oc_apps_domain }}"
        threescale_master_token: "{{threescale_master_token}}"
        threescale_admin_token: "{{threescale_admin_token}}"
        rhsso_namespace: "{{rhsso_namespace}}"

- name: "Install API Workshop"
  hosts: workshop
  tasks:
    - include_role:
        name: provision_sso
      vars:
        eval_rhsso_admin_username: "{{ hostvars['SHARED_VARS']['rhsso_admin_username'] }}"
        eval_rhsso_admin_password: "{{ hostvars['SHARED_VARS']['rhsso_admin_password'] }}"
        ocp_apps_domain: "{{ hostvars['SHARED_VARS']['oc_apps_domain'] }}"        
        configure_only: "true"
        sso_project: "sso"
      tags: sso
    - include_role:
        name: provision_microcks
      vars:
        eval_rhsso_admin_username: "{{ hostvars['SHARED_VARS']['rhsso_admin_username'] }}"
        eval_rhsso_admin_password: "{{ hostvars['SHARED_VARS']['rhsso_admin_password'] }}"
        ocp_apps_domain: "{{ hostvars['SHARED_VARS']['oc_apps_domain'] }}"
      tags: microcks
    - include_role:
        name: setup_che_multi
      vars:
        item: che
        eval_rhsso_admin_username: "{{ hostvars['SHARED_VARS']['rhsso_admin_username'] }}"
        eval_rhsso_admin_password: "{{ hostvars['SHARED_VARS']['rhsso_admin_password'] }}"
        ocp_apps_domain: "{{ hostvars['SHARED_VARS']['oc_apps_domain'] }}"
        openshift_oauth_token: ""
      tags: che
    - include_role:
        name: provision_gogs
      vars:   
        ocp_apps_domain: "{{ hostvars['SHARED_VARS']['oc_apps_domain'] }}"
        configure_only: "false"
      tags: gogs
    - include_role:
        name: provision_threescale
      vars:  
        configure_only: "true"
        eval_rhsso_admin_username: "{{ hostvars['SHARED_VARS']['rhsso_admin_username'] }}"
        eval_rhsso_admin_password: "{{ hostvars['SHARED_VARS']['rhsso_admin_password'] }}"
        ocp_apps_domain: "{{ hostvars['SHARED_VARS']['oc_apps_domain'] }}"
        threescale_master_access_token: "{{ hostvars['SHARED_VARS']['threescale_master_token'] }}"
        threescale_admin_access_token: "{{ hostvars['SHARED_VARS']['threescale_admin_token'] }}"
        sso_project: sso
        threescale_realm: "threescale"
        threescale_client_id: "3scale-admin"
        namespace: 3scale
        no_threescale_services: "false"
      tags: threescale
    - include_role:
        name: provision_apicurio
      vars:
        ocp_apps_domain: "{{ hostvars['SHARED_VARS']['oc_apps_domain'] }}"
        sso_project: sso
        apicurio_template_params: -p API_STUDIO_API_IMAGE_TAG=0.2.17.Final -p API_STUDIO_WS_IMAGE_TAG=0.2.17.Final -p API_STUDIO_UI_IMAGE_TAG=0.2.17.Final
        apicurio_template_url: https://gist.githubusercontent.com/aidenkeating/e14b8150118c6fc2d446ad2644a38d97/raw/2fe99d4b91e7c2d424fc413ca348383a4a378a5b/apicurio-template.yml
        eval_rhsso_admin_username: "{{ hostvars['SHARED_VARS']['rhsso_admin_username'] }}"
        eval_rhsso_admin_password: "{{ hostvars['SHARED_VARS']['rhsso_admin_password'] }}"
      tags: apicurio
    - include_role:
        name: provision_backend
      vars:
        ocp_apps_domain: "{{ hostvars['SHARED_VARS']['oc_apps_domain'] }}"
        sso_project: sso
      tags: backend
    - include_role:
        name: setup_webapp
      vars:
        configmap_name: extra-services
        configmap_namespace: webapp
      tags: webapp
